### ISSUE TITLE
productsign errors

### ISSUE THREAD

**Issue by atlauren** [rustymyers/customBESAgentPkg#4]
There seems to be an issue in the product sign section.  After uncommenting the lines and pasting in the "Developer ID Installer" identity, this error occurs.

```
REDACTED:customBESAgentPkg-master REDACTED$ python customBESAgentPkg.py -s
Found: BESAgent-10.0.1.41-BigFix_MacOSX10.14.pkg
Using Package: ./BESAgent-10.0.1.41-BigFix_MacOSX10.14.pkg
Copying ModifiedFiles...
    Copying: postinstall
    Copying: actionsite.afxm
    Copying: clientsettings.cfg
    Copying: preinstall
signPackage received: 
BESAgent-10.0.1.41-BigFix_MFinished/BESAgent-10.0.1.41-BigFix_MacOSX10.14-REDACTED.pkg
Traceback (most recent call last):
  File "customBESAgentPkg.py", line 252, in <module>
    signPackage(finishedFolder + "/" + unit_package)
  File "customBESAgentPkg.py", line 71, in signPackage
    subprocess.call( command_line_list )
NameError: global name 'subprocess' is not defined`

**Comment by rustymyers** [comment]
Appears I forgot to include subprocess in the imports. Try it with the latest commit

**Comment by atlauren** [comment]
Works.  Closing.
